### ISSUE TITLE
Market app CSS messes up the app menu and top-right menu and also changes the colors.

### ISSUE THREAD

**Issue by davitol** [owncloud/market#54] opened 2017-04-25 08:52 UTC
![screen shot 2017-04-25 at 10 39 22](https://cloud.githubusercontent.com/assets/10596560/25376364/28cabdca-29a4-11e7-9a2c-dae7bd71e81f.png)

![screen shot 2017-04-25 at 10 52 08](https://cloud.githubusercontent.com/assets/10596560/25376765/99e9d0da-29a5-11e7-9d2a-fbf55b0a9c80.png)

![screen shot 2017-04-25 at 10 52 16](https://cloud.githubusercontent.com/assets/10596560/25376715/6a3d6aa4-29a5-11e7-9352-745031d9a44b.png)

In OC
![screen shot 2017-04-25 at 10 26 32](https://cloud.githubusercontent.com/assets/10596560/25376348/18fbdca8-29a4-11e7-967f-86f208f25000.png)
in Market
![screen shot 2017-04-25 at 10 26 21](https://cloud.githubusercontent.com/assets/10596560/25376358/21a88414-29a4-11e7-92e0-f9d0dc96cae9.png)

@felixheidecke

**Comment by PVince81** [comment] 2017-05-17 16:05
is this fixed through https://github.com/owncloud/market/issues/73 ?

**Comment by davitol** [comment] 2017-05-18 07:07
I still can reproduce it

**Comment by DeepDiver1975** [comment] 2017-05-18 07:25
something went wrong with the market build @PVince81 

![bildschirmfoto von 2017-05-18 09-25-01](https://cloud.githubusercontent.com/assets/1005065/26190892/f309a74a-3bab-11e7-9fef-956cb0f96ae4.png)

**Comment by PVince81** [comment] 2017-05-18 07:47
does the market build run correctly locally ? (make dist)

**Comment by DeepDiver1975** [comment] 2017-05-18 07:48
> does the market build run correctly locally ? (make dist)

I'll check ...

**Comment by DeepDiver1975** [comment] 2017-05-18 07:55
okay - issue in the make file ..... taking care ...

**Comment by DeepDiver1975** [comment] 2017-05-18 07:59
hmmm - wrong assumption ... styles are not published in market.min.css ... but where then?

**Comment by DeepDiver1975** [comment] 2017-05-18 07:59
ah - it's all in the js file .....

**Comment by PVince81** [comment] 2017-05-18 08:01
welcome to the webpack century I guess ? (am also susprised)

**Comment by DeepDiver1975** [comment] 2017-05-18 08:13
> I still can reproduce it

please be a bit more precise - what is still reproducible?

**Comment by DeepDiver1975** [comment] 2017-05-18 08:14
looks good to me ...
![bildschirmfoto von 2017-05-18 10-13-56](https://cloud.githubusercontent.com/assets/1005065/26192606/bae7f5f4-3bb2-11e7-93f2-760234f28d79.png)

**Comment by davitol** [comment] 2017-05-18 08:19
![screen shot 2017-05-18 at 10 18 07](https://cloud.githubusercontent.com/assets/10596560/26192820/6353158e-3bb3-11e7-8a05-4cac1d48018d.png)
IMHO it is half-cut.

**Comment by DeepDiver1975** [comment] 2017-05-18 08:20
half cut is related to the theme I guess - but it appears not fixed on your machine .... fucking bullshit

@felixheidecke please apply css wizardry - thx

**Comment by felixheidecke** [comment] 2017-05-18 11:58
Hmmm … does this happen in the CE theme also?

**Comment by felixheidecke** [comment] 2017-05-18 12:04
I am sorry to say, that the changes didn't propagate to *owncloud-enterprise-complete-10.0.1RC1*. That package hasn't been built using the latest changes in market master.

**Comment by felixheidecke** [comment] 2017-05-18 14:06
I pushed some extra CSS for EE

**Comment by SergioBertolinSG** [comment] 2017-07-17 11:41
Safari right menu on current master:

![screen shot 2017-07-17 at 13 38 49](https://user-images.githubusercontent.com/9048796/28266505-7d5aa142-6af5-11e7-8ea0-daf905c4b3c2.png)

**Comment by SergioBertolinSG** [comment] 2017-07-17 14:45
This problem is fixed in firefox, ie 11, chrome and edge in master. But stable10 is not fixed.
THis is using chrome:

![screen shot 2017-07-17 at 16 43 09](https://user-images.githubusercontent.com/9048796/28273618-259f0b7c-6b0f-11e7-9740-c912bd0d1d30.png)

@felixheidecke missed backports in core ? I'm using last version of market app (0.2.1).

**Comment by PVince81** [comment] 2017-08-03 09:53
@felixheidecke please push your new PR.

Moving this to "planned" to finish it for the next release (10.0.4 or whatever market app release comes in between)

**Comment by felixheidecke** [comment] 2017-08-03 10:54
I can not confirm this behavior in the current master 😲 
I am testing with:
![bildschirmfoto vom 2017-08-03 12-53-06](https://user-images.githubusercontent.com/12717530/28918733-dc962f84-784a-11e7-91b9-35cbc0db0f69.png)

**Comment by patrickjahns** [comment] 2017-09-06 14:58
@felixheidecke 

The issue seems to be still remaining in both master/stable10 branch and on chrome for mac:

View in market app
![image](https://user-images.githubusercontent.com/6403243/30118873-663b3b6e-9324-11e7-8331-330b1f4a4fe3.png)

vs 

View in file app
![image](https://user-images.githubusercontent.com/6403243/30118916-83bc3198-9324-11e7-95d3-655eb88d343b.png)

**Closed** 2017-09-11 16:42 UTC
Labels: backport-request, bug, p3-medium, sev3-medium
