### ISSUE TITLE
market - 0.6.0

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/market#574] opened 2020-06-18 07:49 UTC
### Reason

- Release needed for 
- [x] https://github.com/owncloud/market/pull/572
- [x] https://github.com/owncloud/market/pull/573
- [x] Update libraries

### Product approval

- [x] Ping pmaier to check `info.xml` description and screenshot
- [x] Get approval on translations from pmaier

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ... - no commits in last two months 
- [x] Create release branch with the format "release-$version"

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [x] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan =>  @davitol https://github.com/owncloud/market/issues/577

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by HanaGemela** [comment] 2020-06-23 11:22
@davitol RC1 https://github.com/owncloud/market/releases/tag/v0.6.0RC1

**Comment by HanaGemela** [comment] 2020-06-23 11:53
Needs RC2/final rebuild due to https://github.com/owncloud/market/pull/575

**Comment by davitol** [comment] 2020-06-24 06:28
Translations: https://github.com/owncloud/enterprise/issues/3840#issuecomment-648619539

**Comment by davitol** [comment] 2020-06-30 07:08
<img width="956" alt="Screenshot 2020-06-29 at 09 28 11" src="https://user-images.githubusercontent.com/10596560/86094676-2589ff80-bab1-11ea-8516-bb199b2fc0a9.png">


Enterprise key app should no longer be included in the EE bundle for 10.5 core version

**Comment by davitol** [comment] 2020-06-30 08:16
Also should all these app been included in the EE bundle now? https://github.com/owncloud/enterprise/issues/4020#issuecomment-648234614

There are some recently bundled apps like wopi or files classifier

cc @pmaier1 @micbar @IljaN

**Comment by HanaGemela** [comment] 2020-07-02 08:24
@IljaN this has been raised to P2 as this will block the release

**Comment by IljaN** [comment] 2020-07-02 08:49
Problem is that bundle api does not receive a version: https://marketplace.owncloud.com/api/v1/bundles.json. Market app should hide incompatible app versions client-side.

**Comment by IljaN** [comment] 2020-07-02 08:59
@micbar I think this might be fixed if we release an enterprise_key app with max_version < 10.5

**Comment by IljaN** [comment] 2020-07-02 09:02
But we already have an enterprise-key app released with max version 10.x ... hmhhh

**Comment by IljaN** [comment] 2020-07-02 13:02
@HanaGemela @davitol Is the installation of key app causing any errors?

**Comment by jnweiger** [comment] 2020-07-02 14:46
The enterprise_key app is deprecated. We must not try to install it. All remaining logic should be in core by now.

**Comment by IljaN** [comment] 2020-07-02 14:55
I see but there are Problems :tm: : 
We need to support old instances which still use the old licensing scheme. This is not possible by setting version-constraints in marketplace as the "Install bundle" dialog in the market app does not honor the version constraints for an app as the bundle itself has no version constraints.  https://marketplace.owncloud.com/api/v1/bundles.json

**Comment by jnweiger** [comment] 2020-07-02 16:36
Yes, good catch!

We need to support both, 10.4.1 with enterprise-app and all the old enterprise logic, and new 10.5.x which should afaik work without enterprise-app. So second solution would be my suggestion. How much effort is that?

**Comment by davitol** [comment] 2020-07-03 09:24
IMHO I would choose also the second option, patching market app to honor version constraints of bundled apps. Not only for EE key app issue but also for example for adding WOPI to the 10.5 bundle as it was decided

**Comment by IljaN** [comment] 2020-07-03 12:24
Version Constraint on latest enterprise_key app:
```
"releases": [
          {
            "platformMin": "10.0.0",
            "platformMax": "10.9999.9999",
            "version": "0.2.0",
            "url": "https://marketplace.owncloud.com/api/v1/apps/enterprise_key/0.2.0"
          },
```

**Comment by jnweiger** [comment] 2020-07-03 13:01
Adding enterprise-app 0.2.0 to the current 10.5.0-complete bundle with max-version=10.4.1 and without <default_enable/> makes it appear in the diabled apps page as

![image](https://user-images.githubusercontent.com/1108546/86471153-1cad5e00-bd3d-11ea-8840-7acb379a9af0.png)

Having the app there but intended for not being used, is a bit confusing. But the red message is worse. An admin must assume something is wrong.

**Comment by pmaier1** [comment] 2020-07-06 07:43
> Having the app there but intended for not being used, is a bit confusing. But the red message is worse. An admin must assume something is wrong.

The `enterprise_key` app should not be part of the 10.5 bundle. The logic has moved to core and the app is deprecated. That's why we re-release it with the version constraint in the first place.

**Comment by jnweiger** [comment] 2020-07-06 08:19
@pmaier1 IIRC, the decision on Friday was to include the enterprise_key app and work on the symptoms. No?

**Comment by pmaier1** [comment] 2020-07-06 08:27
> @pmaier1 IIRC, the decision on Friday was to include the enterprise_key app and work on the symptoms. No?

If I'm not totally mistaken, the decision was to re-release it with a max-version=10.4.1 to prevent people on 10.5 from installing it from the Marketplace. Other than that 10.4.1 is the last version that includes it.

@micbar Please enlighten us :)

**Comment by micbar** [comment] 2020-07-06 08:30
If it is possible, remove. it from the bundle for 10.5

@pmaier1 The problem is, we still need it for 10.4.1. These instances need to fetch it from the marketplace.

So we said: if we cannot make the disctinction on the marketplace, we need to keep it in the bundle.

**Comment by jnweiger** [comment] 2020-07-06 09:31
@IljaN would that work for you? Can you work on this p2 ?

**Comment by IljaN** [comment] 2020-07-06 12:13
@jnweiger Not sure If I understand enteprise_key is already in the bundle?

**Comment by davitol** [comment] 2020-07-06 12:26
> we do a re-release to market place only with max-version=10.4 correct?

10.4.1

> @jnweiger Not sure If I understand enteprise_key is already in the bundle on marketplace?

Enterprise key app is currently included in the marketplace EE bundle. @jnweiger won't include enterprise key app in the apps that are included in the complete tarball.

**Comment by jnweiger** [comment] 2020-07-10 09:49
@IljaN can we release this market app as is, or do you have any last minute changes from yesterday's hacking session?

**Comment by davitol** [comment] 2020-07-14 11:25
@IljaN Testing market 0.6.0 RC2 included in ownCloud 10.5.1. RC4

**Testing steps:**

1 - Browse to the bundle section and install market bundle

**Current behavior**

A blank page appears in the browser and if you reload the browser, Internal server error is shown.

Content of owncloud.log file below

`{"reqId":"4Zt5EYRabciOK9umgMVz","level":3,"time":"2020-07-14T11:20:36+00:00","remoteAddr":"172.18.0.1","user":"12345","app":"no app in context","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"enterprise_key can't be enabled since it is not installed.\",\"Code\":0,\"Trace\":\"#0 \\\/mnt\\\/data\\\/apps\\\/objectstore\\\/appinfo\\\/app.php(19): OC\\\\App\\\\AppManager->enableApp()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(239): require_once('\\\/mnt\\\/data\\\/apps\\\/...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(190): OC_App::requireAppFile()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(124): OC_App::loadApp()\\n#4 \\\/var\\\/www\\\/owncloud\\\/ocs\\\/v1.php(58): OC_App::loadApps()\\n#5 \\\/var\\\/www\\\/owncloud\\\/ocs\\\/v2.php(23): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/App\\\/AppManager.php\",\"Line\":243}"}
{"reqId":"4Zt5EYRabciOK9umgMVz","level":2,"time":"2020-07-14T11:20:36+00:00","remoteAddr":"172.18.0.1","user":"12345","app":"core","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"Could not load app \"objectstore\", see exception above"}
{"reqId":"4Zt5EYRabciOK9umgMVz","level":3,"time":"2020-07-14T11:20:36+00:00","remoteAddr":"172.18.0.1","user":"12345","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"Exception: enterprise_key can't be enabled since it is not installed. at \/var\/www\/owncloud\/lib\/private\/App\/AppManager.php#243"}
{"reqId":"ZWCbXb7VaVn0VVjl92R9","level":3,"time":"2020-07-14T11:20:55+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"objectstore","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"Enabling Enterprise license app which was deactivated."}
{"reqId":"ZWCbXb7VaVn0VVjl92R9","level":3,"time":"2020-07-14T11:20:55+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"no app in context","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"enterprise_key can't be enabled since it is not installed.\",\"Code\":0,\"Trace\":\"#0 \\\/mnt\\\/data\\\/apps\\\/objectstore\\\/appinfo\\\/app.php(19): OC\\\\App\\\\AppManager->enableApp()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(239): require_once('\\\/mnt\\\/data\\\/apps\\\/...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(190): OC_App::requireAppFile()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(124): OC_App::loadApp()\\n#4 \\\/var\\\/www\\\/owncloud\\\/ocs\\\/v1.php(58): OC_App::loadApps()\\n#5 \\\/var\\\/www\\\/owncloud\\\/ocs\\\/v2.php(23): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/App\\\/AppManager.php\",\"Line\":243}"}
{"reqId":"ZWCbXb7VaVn0VVjl92R9","level":2,"time":"2020-07-14T11:20:55+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"core","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"Could not load app \"objectstore\", see exception above"}
{"reqId":"ZWCbXb7VaVn0VVjl92R9","level":3,"time":"2020-07-14T11:20:55+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"Exception: enterprise_key can't be enabled since it is not installed. at \/var\/www\/owncloud\/lib\/private\/App\/AppManager.php#243"`

**Comment by IljaN** [comment] 2020-07-14 11:32
I think the problem is within the objectstore app which tries to enable enterprise_key app which is not installed. From my POV a new release of objecstore app is required which remove the license-check from the. 

@davitol Could you please repeat the test with disabled objectstore app to verify?

**Comment by davitol** [comment] 2020-07-14 11:56
staging enviroment needs to get the latest objectstore version 0.6.0. It is still with the old data

**Comment by davitol** [comment] 2020-07-14 16:27
@jnweiger @HanaGemela LGTM :shipit:

**Closed** 2020-07-15 12:38 UTC
Labels: QA-ready, orga, p2-high
