### ISSUE TITLE
Integrity check fails

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/market#279] opened 2018-03-06 21:59 UTC
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- market
	- EXTRA_FILE
		- README.md

Raw output
==========
Array
(
    [market] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => b53ebb407cb90a5cf9e28463013f38e6aec3d39b4281187366e02b5fd014be144216a088fc50851635acc50cb71c92ad2407b21e8a4f3433b0f73a32ea066c97
                        )
                )
        )
)
```

**Comment by IljaN** [comment] 2018-03-07 10:11
- How did you install market app?
- Which market app version are you using?

Could you please post the contents of /$OWNCLOUDDIR/apps/market/appinfo/signature.json

Thanks!

**Comment by IljaN** [comment] 2018-03-07 11:09
Duplicate of #226

**Comment by patrickjahns** [comment] 2018-04-22 18:44
closing as duplicate of #226

**Closed by patrickjahns** 2018-04-22 18:44 UTC
