### ISSUE TITLE
Weird problem installing using occ market:install

### ISSUE THREAD

**Issue by davitol** [owncloud/market#486] opened 2019-06-12 06:57 UTC
When you install enterprise tarball using the CLI (occ market:install), the new version of market app is installing under apps-external folder which folder is the writable one in the config.php and the old version is still remaining under apps folder.

After the installation the ownCloud instance is somehow loading old app's js file. If you remove the old app from apps folder, the problem is solved. We need tp nvestigate the behavior of occ market:install' command.

Tested with tarball 10.2 EE complete and spotted here https://github.com/owncloud/market/pull/468#issuecomment-500720829

**Comment by patrickjahns** [comment] 2019-06-13 11:04
@davitol 

Can you reliably reproduce this issue ?

**Comment by davitol** [comment] 2019-06-13 11:14
@patrickjahns I think yes, **e.g.** using tarball 10.2 EE complete tarball and  ```market:install -l market-0.5.0.tar.gz```

**Comment by davitol** [comment] 2019-06-20 10:27
Reproduced continuously, now with activity app. So no matter which app is the one to be updated

**Comment by patrickjahns** [comment] 2019-06-21 10:20
I can reproduce this as well.

@davitol 
Can you share your config report? Do you have APCU enabled ?

**Comment by patrickjahns** [comment] 2019-06-21 11:02
Running into strange issues as well when testing the 0.5 RC app in the docker container
```
{"reqId":"cSCUrARlrUFvBB3SZTqb","level":3,"time":"2019-06-21T10:43:37+00:00","remoteAddr":"172.17.0.1","user":"admin","app":"index","method":"GET","url":"\/apps\/market\/apps","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(124): OC_App::loadApp('market')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(894): OC_App::loadApps()\\n#2 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#3 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":188}"}
``` 

Initial problem related to fetching old javascript might be because of 
https://github.com/owncloud/market/blob/master/templates/index.php#L23

Which leads to https://github.com/owncloud/core/blob/master/lib/private/legacy/template/functions.php#L54-L62 and respective https://github.com/owncloud/core/blob/master/lib/private/legacy/util.php#L522 

In the container context - the resources should not be loaded from:
- owncloud/apps/market/market.bundle.js
but
- owncloud/custom/market/market.bundle.js 

It seems that owncloud would map it accordingly, if the path couldn't be found in the first route. But leads to weird other parts. Wasn't able to dig deeper into yet

**Comment by VicDeo** [comment] 2019-06-21 14:43
@davitol the behavior is correct unless `apps` is marked as writable in config.php
if apps is non-writable we can't do anything with apps inside it.
See the expectations in https://github.com/owncloud/core/issues/35031 

The only issue I see here is 
> After the installation the ownCloud instance is somehow loading old app's js file.

but it's unrelated to market.

**Comment by davitol** [comment] 2019-06-24 08:39
>  Do you have APCU enabled ?



> Can you share your config report? Do you have APCU enabled ?

APCU not enabled

Config report here:

https://cloud.owncloud.com/index.php/s/oWyWK1MUCnd040S

**Comment by VicDeo** [comment] 2019-06-24 11:41
Not a bug.  see above.

**Comment by davitol** [comment] 2019-06-24 11:47
> After the installation the ownCloud instance is somehow loading old app's js file.

So maybe best solution is to open a new ticket in core for tracking this stuff and close this one

**Closed** 2019-06-24 12:00 UTC
Labels: QA-team, bug, discussion, needs info

**Comment by davitol** [comment] 2019-06-24 12:07
New ticket  https://github.com/owncloud/core/issues/35640
