### ISSUE TITLE
Nav bar settings dropdown styles changed whilst in market app

### ISSUE THREAD

**Issue by tomneedham** [owncloud/market#70] opened 2017-05-09 09:58 UTC
In any other app / page of owncloud:
![screen shot 2017-05-09 at 11 56 28](https://cloud.githubusercontent.com/assets/660805/25845559/a98edad0-34ae-11e7-9b88-e99870dca380.png)
whilst viewing the market app (chrome browser)
![screen shot 2017-05-09 at 11 56 22](https://cloud.githubusercontent.com/assets/660805/25845569/b2384dc4-34ae-11e7-8575-d3741fbb6f79.png)
running master OC 10 and master branch market app

**Comment by felixheidecke** [comment] 2017-05-29 14:00
Duplicate of https://github.com/owncloud/market/issues/54

**Closed by felixheidecke** 2017-05-29 14:00 UTC
Labels: bug
